# message: success
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    lease-renewal-interval-in-seconds: 35
    prefer-ip-address: true
